# frozen_string_literal: true

source 'https://rubygems.org'

gem 'mongoid'
gem 'newrelic-slack-ruby-bot'
gem 'slack-ruby-bot-server', github: 'dblock/slack-ruby-bot-server', branch: 'extract-rtm'
gem 'slack-ruby-bot-server-rtm', path: '../../'

gem 'kaminari-mongoid'
gem 'mongoid-scroll'
gem 'unicorn'

group :test do
  gem 'database_cleaner'
  gem 'fabrication'
  gem 'faker'
  gem 'rack-test'
  gem 'rake'
  gem 'rspec'
  gem 'vcr'
  gem 'webmock'
end
