default: &default
  adapter: postgresql
  pool: 10
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: slack_ruby_bot_server_development

test:
  <<: *default
  database: slack_ruby_bot_server_test
  url: <%= ENV["DATABASE_URL"] || 'postgres://localhost/slack_ruby_bot_server_test' %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
