# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord'
gem 'mutex_m'
gem 'newrelic-slack-ruby-bot'
gem 'otr-activerecord'
gem 'pagy_cursor'
gem 'pg'
gem 'rack-server-pages'
gem 'rack-test'
gem 'slack-ruby-bot-server-rtm', path: '../../'
gem 'unicorn'

group :development, :test do
  gem 'standalone_migrations'
end

group :test do
  gem 'database_cleaner'
  gem 'fabrication'
  gem 'faker'
  gem 'rake'
  gem 'rspec'
  gem 'vcr'
  gem 'webmock'
end
